### ISSUE TITLE
Click on toggle icon should open/close panel

### ISSUE THREAD

**Issue by stenzengel** [mouellet/vaadin-stackpanel#3]
When clicking on the toggle icon, nothing happens. I had expected, that clicking on the icon would open or close the panel.

**Comment by akamos** [comment]
It's a real bug, I'm still fixing it. If you click in the middle on panel it works!

**Comment by akamos** [comment]
fixed in fbe46c344b66ad7386a8fc987b5701c7c8fae0d6
