### ISSUE TITLE
panel is not openning\closing when there is icon with html caption

### ISSUE THREAD

**Issue by yinon111** [mouellet/vaadin-stackpanel#9]
I am using HTML for the caption with icon  , and the problem I am facing is that the panel is not openning and closing while clicking  on the caption. 
When clicking the '+' sign or the icon or any white space (where there is no text) the panel responding and openning and closing as expected but when clicking the text caption it does not respond.

**Comment by yinon111** [comment]
This is how I use it:

![capture](https://cloud.githubusercontent.com/assets/21983892/18230775/76eec01c-72ae-11e6-89e8-56a2992daf44.png)

**Comment by mouellet** [comment]
Hi @yinon111, thanks for reporting this issue.

Looks like the problem is with the icon and not caption as html. I'll be releasing a new version shortly.

**Comment by yinon111** [comment]
Thank you so much for the fast fix !
